import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";
import Link from "next/link";
import { SignOutButton, UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <nav>
              <div className="navbar bg-base-100">
                <div className="flex-1">
                  <Link
                    href="/journal"
                    className="btn btn-ghost normal-case text-xl"
                  >
                    Mood.ai
                  </Link>
                </div>
                <div className="flex-none gap-2">
                  <div className="form-control">
                    <input
                      type="text"
                      placeholder="Search"
                      className="input input-bordered w-24 md:w-auto"
                    />
                  </div>
                  <div className="dropdown dropdown-end">
                    <div className="h-full w-full px-6 flex items-center justify-end">
                      <UserButton afterSignOutUrl="/" />
                    </div>
                  </div>
                </div>
              </div>
            </nav>
          </header>
          <div>{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
